name: fluid_animations
description: Create effortlessly smooth and responsive animations inspired by SwiftUI's spring animations.
version: 1.0.0
repository: https://github.com/RoundedInfinity/fluid_animations

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.18.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ">=5.1.0 <7.0.0"
